# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: "Marc Fede Space"
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics: null
  locale: en-US
  baseUrl: "marcfede.github.io/quartz"
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: googleFonts
    cdnCaching: true
    typography:
      header: "Schibsted Grotesk"
      body: "Source Sans Pro"
      code: "IBM Plex Mono"
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#2b6cb0"
        tertiary: "#845ef7"
        highlight: "rgba(143, 157, 172, 0.15)"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b2cbf"
        tertiary: "#9d4edd"
        highlight: "rgba(143, 157, 172, 0.15)"
plugins:
  transformers:
    - name: FrontMatter
    - name: GitHubFlavoredMarkdown
    - name: ObsidianFlavoredMarkdown
    - name: SyntaxHighlighting
    - name: MarkdownLinks
  filters:
    - name: RemoveDrafts
  emitters:
    - name: Aliases
    - name: FolderPage
    - name: TagPage
    - name: ContentIndex
    - name: ContentPage
